#!/bin/bash

echo "📊 進捗を集計中..."

# カウント変数
EASY_TOTAL=0
EASY_SOLVED=0
MEDIUM_TOTAL=0
MEDIUM_SOLVED=0
HARD_TOTAL=0
HARD_SOLVED=0
EXTREME_TOTAL=0
EXTREME_SOLVED=0

# 各難易度のディレクトリをカウント
for dir in solutions/easy/*; do
  [ -d "$dir" ] && ((EASY_TOTAL++))
  if [ -f "$dir/solution.ts" ]; then
    # TODOが残っていないかチェック
    ! grep -q "TODO" "$dir/solution.ts" && ((EASY_SOLVED++))
  fi
done

for dir in solutions/medium/*; do
  [ -d "$dir" ] && ((MEDIUM_TOTAL++))
  if [ -f "$dir/solution.ts" ]; then
    ! grep -q "TODO" "$dir/solution.ts" && ((MEDIUM_SOLVED++))
  fi
done

for dir in solutions/hard/*; do
  [ -d "$dir" ] && ((HARD_TOTAL++))
  if [ -f "$dir/solution.ts" ]; then
    ! grep -q "TODO" "$dir/solution.ts" && ((HARD_SOLVED++))
  fi
done

for dir in solutions/extreme/*; do
  [ -d "$dir" ] && ((EXTREME_TOTAL++))
  if [ -f "$dir/solution.ts" ]; then
    ! grep -q "TODO" "$dir/solution.ts" && ((EXTREME_SOLVED++))
  fi
done

TOTAL_ATTEMPTS=$((EASY_TOTAL + MEDIUM_TOTAL + HARD_TOTAL + EXTREME_TOTAL))
TOTAL_SOLVED=$((EASY_SOLVED + MEDIUM_SOLVED + HARD_SOLVED + EXTREME_SOLVED))

# progress.mdを生成
cat > progress.md << EOF
# 📈 Type Challenges Progress

最終更新: $(date '+%Y-%m-%d %H:%M:%S')

## 📊 統計サマリー
- **総チャレンジ数**: ${TOTAL_ATTEMPTS}
- **完了数**: ${TOTAL_SOLVED}
- **完了率**: $([ $TOTAL_ATTEMPTS -gt 0 ] && echo "scale=1; $TOTAL_SOLVED * 100 / $TOTAL_ATTEMPTS" | bc || echo 0)%

## 🏆 難易度別進捗

### 🟢 Easy
- 試行: ${EASY_TOTAL}
- 完了: ${EASY_SOLVED}
- 進捗: $([ $EASY_TOTAL -gt 0 ] && echo "scale=1; $EASY_SOLVED * 100 / $EASY_TOTAL" | bc || echo 0)%

### 🟡 Medium  
- 試行: ${MEDIUM_TOTAL}
- 完了: ${MEDIUM_SOLVED}
- 進捗: $([ $MEDIUM_TOTAL -gt 0 ] && echo "scale=1; $MEDIUM_SOLVED * 100 / $MEDIUM_TOTAL" | bc || echo 0)%

### 🔴 Hard
- 試行: ${HARD_TOTAL}
- 完了: ${HARD_SOLVED}
- 進捗: $([ $HARD_TOTAL -gt 0 ] && echo "scale=1; $HARD_SOLVED * 100 / $HARD_TOTAL" | bc || echo 0)%

### 🟣 Extreme
- 試行: ${EXTREME_TOTAL}
- 完了: ${EXTREME_SOLVED}
- 進捗: $([ $EXTREME_TOTAL -gt 0 ] && echo "scale=1; $EXTREME_SOLVED * 100 / $EXTREME_TOTAL" | bc || echo 0)%

## 📅 活動履歴
$(ls -1 logs/daily/*.md 2>/dev/null | tail -5 | while read f; do echo "- [$(basename $f .md)](${f})"; done)

---
*Generated by progress.sh*
EOF

# README.mdを更新
cat > README.md << EOF
# 🚀 My Type Challenges Journey

![](https://img.shields.io/badge/Solved-${TOTAL_SOLVED}-green)
![](https://img.shields.io/badge/Attempted-${TOTAL_ATTEMPTS}-blue)
![](https://img.shields.io/badge/Success_Rate-$([ $TOTAL_ATTEMPTS -gt 0 ] && echo "scale=0; $TOTAL_SOLVED * 100 / $TOTAL_ATTEMPTS" | bc || echo 0)%25-orange)

## 📚 概要

TypeScript型システムの深い理解を目指して、[Type Challenges](https://github.com/type-challenges/type-challenges)に挑戦しています。

## 🎯 現在の進捗

\`\`\`
総完了数: ${TOTAL_SOLVED} / ${TOTAL_ATTEMPTS}
完了率: $([ $TOTAL_ATTEMPTS -gt 0 ] && echo "scale=1; $TOTAL_SOLVED * 100 / $TOTAL_ATTEMPTS" | bc || echo 0)%

Easy:    $EASY_SOLVED / $EASY_TOTAL
Medium:  $MEDIUM_SOLVED / $MEDIUM_TOTAL  
Hard:    $HARD_SOLVED / $HARD_TOTAL
Extreme: $EXTREME_SOLVED / $EXTREME_TOTAL
\`\`\`

## 🛠️ 環境

- **Node.js**: v24
- **TypeScript**: Latest
- **Linter/Formatter**: ESLint (オリジナルtype-challenges準拠)
- **Test Runner**: Vitest
- **IDE**: VS Code with Dev Container

## 📁 プロジェクト構造

\`\`\`
my-type-challenges/
├── original-type-challenges/  # サブモジュール（本家）
├── solutions/                 # 自分の解答
│   ├── easy/
│   ├── medium/
│   ├── hard/
│   └── extreme/
├── scripts/                   # 自動化スクリプト
├── logs/                      # 学習ログ
└── utils/                     # ユーティリティ型
\`\`\`

## 📖 詳細

詳しい進捗は [progress.md](./progress.md) をご覧ください。

---
*Last updated: $(date '+%Y-%m-%d %H:%M:%S')*
EOF

# ESLintでフォーマット
npx eslint progress.md README.md --fix 2>/dev/null || true

git add progress.md README.md
git commit -m "📊 Update progress: ${TOTAL_SOLVED}/${TOTAL_ATTEMPTS} solved

- Easy: ${EASY_SOLVED}/${EASY_TOTAL}
- Medium: ${MEDIUM_SOLVED}/${MEDIUM_TOTAL}
- Hard: ${HARD_SOLVED}/${HARD_TOTAL}
- Extreme: ${EXTREME_SOLVED}/${EXTREME_TOTAL}"

echo "✅ 進捗を更新しました！"
echo "📈 完了: ${TOTAL_SOLVED}/${TOTAL_ATTEMPTS}"
